buildscript {
    ext {
        springBootVer = '3.5.16'
    }
}

plugins {
    id 'java'
    id 'idea'
    id 'checkstyle'
    id 'jacoco'
    id 'org.springframework.boot' version "${springBootVer}"
    id 'com.gorylenko.gradle-git-properties' version '2.5.7'
}

apply plugin: 'idea'
apply plugin: 'io.spring.dependency-management'

group = 'com.untalsanders.contact-book'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    // Production ------------------------------------------------------------------//

    //-- Spring Boot Dependencies all inherit from the spring-boot-starter-parent --//
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Third-party dependencies
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

    implementation 'org.apache.commons:commons-lang3'
    implementation libs.springdoc.openapi.starter.webmvc.ui
    implementation libs.mapstruct

    // Runtime ---------------------------------------------------------------------//

    //-- Data stores and supporting libs --//
    runtimeOnly libs.h2
    //runtimeOnly libs.hsqldb
    runtimeOnly libs.postgres

    // Compile ---------------------------------------------------------------------//
    compileOnly libs.lombok

    // Annotation Processors
    annotationProcessor libs.lombok
    annotationProcessor libs.mapstruct.processor

    // Test ------------------------------------------------------------------------//
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    checkstyle "com.puppycrawl.tools:checkstyle:${checkstyle.toolVersion}"

    // Development -----------------------------------------------------------------//
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
}

test {
    testLogging {
        /*events "passed", "skipped", "failed"*/
        showStandardStreams = true
    }
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = false
        csv.required = false
        html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
    }
}

jacocoTestCoverageVerification {
    dependsOn jacocoTestReport

    violationRules {
        rule {
            enabled = true
            limit {
                minimum = 0.05
            }
        }
    }
}

jar {
    enabled = false
}

javadoc {
    include 'com/untalsanders/contacts/domain/**'
}

checkstyle {
    toolVersion = "10.12.4"
}
