spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:contact-book-db
    username: sa
    password:
  sql:
    init:
      # SQL is written to be idempotent so this is safe
      mode: always
      schema-locations: classpath*:db/${database.db-engine:hsqldb}/schema.sql
      data-locations: classpath*:db/${database.db-engine:hsqldb}/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

# Security config
#  security:
#    user:
#      name: sanders
#      password: 12345

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

contacts:
  trace: ${CONTACT_TRACE:false}
