spring:
  devtools:
    add-properties: false
  datasource:
    driver-class-name: ${database.db-driver-class-name:org.postgresql.Driver}
    url: jdbc:${database.db-driver:postgresql}://${database.db-host:localhost}:${database.db-port:5432}/${database.db-name:contactbook}
    username: ${database.db-user:postgres}
    password: ${database.db-pass:12345}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    open-in-view: false
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

database:
  db-driver: ${DB_DRIVER}
  db-driver-class-name: ${DB_DRIVER_CLASSNAME}
  db-host: ${DB_HOST}
  db-port: ${DB_PORT}
  db-name: ${DB_NAME}
  db-user: ${DB_USER}
  db-pass: ${DB_PASS}
