# Contact Book API

@email=sanders@domain.com
@password=S3cret12345

###
# group: Authentication
# @name Register User
POST {{BASE_URL}}/api/v1/auth/register
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}


###
# group: Authentication
# @name Login User
POST {{BASE_URL}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}
