# Contacts API

@user=sanders
@password=12345

###
# group: Contacts
# @name List Contacts
GET {{BASE_URL}}/api/v1/contacts
# Authorization: Basic {{user}} {{password}}

> {%
    client.test("GET all contacts returns 200", function () {
        client.assert(response.status === 200, "Expected 200 but was: " + response.status)
    })
%}

###
# group: Contacts
# @name Save Contact
POST {{BASE_URL}}/api/v1/contacts?trace=true
Content-Type: application/json

{
    "firstName": "Jackelin",
    "lastName": "Cadavid",
    "phoneNumber": "1158643071"
}

> {%
    client.test("Save Contact returns 201", function () {
        client.assert(response.status === 201, "Expected 201 but was: " + response.status)
    })
%}

###
@id=4
# group: Contacts
# @name Get Contact
GET {{BASE_URL}}/api/v1/contacts/{{id}}?trace=true

> {%
    client.test("Get Contact returns 200", function () {
        client.assert(response.status === 200, "Expected 200 but was: " + response.status)
    })
%}

###
# group: Contacts
# @name Update Contact
PUT {{BASE_URL}}/api/v1/contacts/{{id}}
Content-Type: application/json

{
    "firstName": "Jackelin",
    "lastName": "Cadavid",
    "phone": "0541158643072"
}

> {%
    client.test("Update Contact returns 201", function () {
        client.assert(response.status === 201, "Expected 201 but was: " + response.status)
    })
%}

###
# group: Contacts
# @name Delete Contact
DELETE {{BASE_URL}}/api/v1/contacts/{{id}}

> {%
    client.test("Delete Contact returns 200", function () {
        client.assert(response.status === 200, "Expected 200 but was: " + response.status)
        client.assert(response.body["deleted"] == true, "Expected object key \"deleted\" equal to \"true\" word but was: " + response.body)
    })
%}


###
# group: Authentication
# @name Register User
POST {{BASE_URL}}/api/v1/auth/register
Content-Type: application/json

{
    "email": "sanders@domain.com",
    "password": "S3cret12345"
}


###
# group: Authentication
# @name Login User
POST {{BASE_URL}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}
