@startuml "Contacts API - Use Cases Diagram C4Model"
!include styles.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

left to right direction

title Use Cases Diagram MS-Contacts

skinparam packageStyle rectangle

package "Contacts" {
    usecase "List Contacts" as US1
    usecase "View Contact" as US2
    usecase "Create Contact" as US3
    usecase "Update Contact" as US4
    usecase "Delete Contact" as US5
}

actor :User: as User

User --> (US1)
User --> (US2)
User --> (US3)
User --> (US4)
User --> (US5)

caption \nFigure 3: [Use Cases] MS-Contacts
footer diagram created with PlantUML v. %version() y C4-PlantUML v. C4Version()
@enduml
